CREATE DATABASE retail_db;
USE retail_db;

-- Q1. What is the total revenue generated by male vs. female customers?

SELECT SUM(purchase_amount) as revenue, gender
from customer_data
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount
FROM customer_data
WHERE discount_applied = "yes" and purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_data);

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased, ROUND(AVG(review_rating),2) as "Average Product Rating"
FROM customer_data
GROUP BY item_purchased
ORDER BY AVG(review_rating) desc
LIMIT 5;


-- Q4. Correlates shipping type with both spending behavior and customer satisfaction
SELECT 
    shipping_type, review_rating,
    COUNT(customer_id) as volume,
    ROUND(AVG(purchase_amount), 2) as avg_order_value,
    ROUND(AVG(review_rating), 2) as avg_satisfaction,
    -- Calculate how many use discounts with each shipping type
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) as discount_users
FROM customer_data
GROUP BY shipping_type, review_rating
HAVING COUNT(customer_id) > 5 -- Filter out rare shipping methods for statistical significance
ORDER BY avg_order_value DESC;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue
-- between subscribers and non-subscribers

SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount) ,2) AS avg_spend,
ROUND (SUM(purchase_amount) ,2) AS total_revenue
FROM customer_data
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_rate desc
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total
-- number of previous purchases, and show the count of each segment.
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE
WHEN previous_purchases = 1 THEN 'New'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal'
END AS customer_segment
FROM customer_data
)
SELECT customer_segment, count(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

-- Q8. Calculates the revenue contribution percentage of the top 3 items within each category
WITH CategoryRevenue AS (
    SELECT 
        category, 
        item_purchased,
        SUM(purchase_amount) AS item_rev,
        SUM(SUM(purchase_amount)) OVER(PARTITION BY category) AS total_cat_rev
    FROM customer_data
    GROUP BY category, item_purchased
),
RankedItems AS (
    SELECT *,
        DENSE_RANK() OVER(PARTITION BY category ORDER BY item_rev DESC) as item_rank,
        ROUND(100.0 * item_rev / total_cat_rev, 2) as pct_contribution
    FROM CategoryRevenue
)
SELECT category, item_purchased, item_rev, pct_contribution
FROM RankedItems
WHERE item_rank <= 3;

-- Q9. Identify loyal customers who have a subscription but have a 
-- long purchase frequency, suggesting they might cancel soon.
SELECT 
    customer_id,
    age_group,
    previous_purchases,
    purchase_frequency_days,
    subscription_status,
    CASE 
        WHEN purchase_frequency_days > 60 AND subscription_status = 'Yes' THEN 'High Churn Risk'
        WHEN purchase_frequency_days > 60 AND subscription_status = 'No' THEN 'Lapsed Customer'
        ELSE 'Active'
    END AS retention_status
FROM customer_data
WHERE previous_purchases > 10
ORDER BY purchase_frequency_days DESC;

-- Q10. What is the revenue contribution of each age group?

SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customer_data
GROUP BY age_group
ORDER BY total_revenue desc;

-- Q11. Identify VIPs: Customers who spend more than the average, 
-- have a high rating, and have a high lifetime purchase count.

WITH GlobalStats AS (
    SELECT AVG(purchase_amount) as avg_spend FROM customer_data
)
SELECT 
    customer_id,
    age_group,
    previous_purchases,
    purchase_amount,
    review_rating,
    CASE 
        WHEN purchase_amount > (SELECT avg_spend FROM GlobalStats) * 1.5 AND previous_purchases > 20 THEN 'Diamond VIP'
        WHEN purchase_amount > (SELECT avg_spend FROM GlobalStats) AND previous_purchases > 10 THEN 'Gold Member'
        ELSE 'Standard'
    END AS customer_tier
FROM customer_data
WHERE review_rating >= 4.0
ORDER BY purchase_amount DESC;